export const SET_SHOW_ADD_TO_CART_MODAL = "SET_SHOW_ADD_TO_CART_MODAL";
export const SET_ITEMS = "SET_ITEMS";
export const SET_LOADING = "SET_LOADING";
export const SET_OPENED_CARD_MODAL = "SET_OPENED_CARD_MODAL";